#!/usr/bin/env python3
"""Measure PALETTE.SHD's thirty-two rows as scalar brightness multipliers.

The shaded rasterizer's output is `PALETTE.SHD[row][texel]` -- a palette
index in, a palette index out (TOTALA-EXE-SHADING.md S:09). RWE renders from
an RGBA texture atlas and no longer has the texel's palette index at the
fragment, so it cannot do that lookup directly. What it can do is apply the
row's average effect as a multiplier, and this is what measures it.

The average is over every palette entry bright enough to carry a ratio,
weighted equally, which is the same population section 09 of the document
measured. Two properties of the real table survive that averaging and are the
whole reason for not using the `0.06875 * row` its fallback generator
suggests: the bright half saturates hard (row 31 is 1.807x, not 2.131x,
because a nearest-neighbour search runs out of palette to move to), and row 0
is a genuine zero.

What does NOT survive is that the saturation is per colour: index 250, a
pure green, comes back unchanged at every row from 14 to 31, while a mid grey
brightens by 80%. Reproducing that needs the palette index carried through
the atlas per texel. See S:15 item 6.

Usage:
    python shdramp.py [path-to-palettes-dir]      # prints the GLSL array
    python shdramp.py --table                     # prints a readable table
"""

import sys
import os

DEFAULT_DIR = r"D:\RWE-extract\totala1\palettes"


def luminance(c):
    return 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2]


def measure(palettes_dir):
    with open(os.path.join(palettes_dir, "PALETTE.SHD"), "rb") as f:
        shd = f.read()
    with open(os.path.join(palettes_dir, "PALETTE.PAL"), "rb") as f:
        pal = f.read()
    if len(shd) != 8192:
        raise SystemExit("PALETTE.SHD is %d bytes, expected 8192" % len(shd))
    if len(pal) != 1024:
        raise SystemExit("PALETTE.PAL is %d bytes, expected 1024" % len(pal))

    rgb = [(pal[i * 4], pal[i * 4 + 1], pal[i * 4 + 2]) for i in range(256)]

    rows = []
    for row in range(32):
        ratios = []
        for i in range(256):
            incoming = luminance(rgb[i])
            # Too dark to carry a meaningful ratio, and the palette's very
            # dark end is mostly the shade ramps themselves.
            if incoming <= 4.0:
                continue
            outgoing = luminance(rgb[shd[row * 256 + i]])
            ratios.append(outgoing / incoming)
        rows.append(sum(ratios) / len(ratios))
    return rows


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    palettes_dir = args[0] if args else DEFAULT_DIR
    rows = measure(palettes_dir)

    if "--table" in sys.argv:
        print("row | multiplier | reachable at a vertex?")
        for i, v in enumerate(rows):
            reachable = "yes" if (i <= 6 or i >= 26) else ("yes (DONT_SHADE)" if i == 15 else "")
            print("%3d | %10.4f | %s" % (i, v, reachable))
        return

    print("// Generated by tools/exe/shading/shdramp.py from %s" % palettes_dir)
    print("// PALETTE.SHD row -> mean brightness multiplier. Do not hand-edit.")
    print("const float shadeTable[32] = float[32](")
    for i in range(0, 32, 4):
        chunk = ", ".join("%.4f" % v for v in rows[i:i + 4])
        comma = "," if i + 4 < 32 else ");"
        print("    %s%s" % (chunk, comma))


if __name__ == "__main__":
    main()
