#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["scapy"]
# ///
"""Turn the spike's captures into the hex in src/rwe/net/ta/ta_packet_captures.h.

    uv run tools/ta-net/ta-packet-captures.py            rewrite the header
    uv run tools/ta-net/ta-packet-captures.py --audit    only print what would go in it

Every TA packet in the captures is deduplicated on its wire bytes, so a shape that
repeats through a session is stored once; the captures hold 2907 packets and 1497
distinct ones. Nothing identifying goes in: the payloads carry no address and no
name, only the stock map names the 0x20 player status carries, and the --audit pass
prints every printable run it can find so that stays checkable.
"""
import re
import struct
import sys
from collections import OrderedDict

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from tanet import decompress, decrypt, read_capture, split_subpackets, ta_payload  # noqa

CAPTURES = [
    ("baseline", "/home/oscar/source/repos/.RWE-B4.worktrees/ta-baseline.pcap"),
    ("options", "/home/oscar/source/repos/.RWE-B4.worktrees/ta-options.pcap"),
    ("small", "/home/oscar/source/repos/.RWE-B4.worktrees/ta-small.pcap"),
]

HEADER = """#pragma once

// Every distinct TA packet in the spike's captures, as it came off the wire.
//
// Generated by tools/ta-net/ta-packet-captures.py from ta-baseline.pcap,
// ta-options.pcap and ta-small.pcap, the three recordings of a real Total
// Annihilation playing over DirectPlay that the spike took. 2907 packets, 1497
// distinct on their wire bytes, both types (0x03 plain, 0x04 compressed) and both
// shapes of the u32 at offset 3 (0xffffffff on replies, a per-sender count that
// falls from 0xffffff on its own traffic) between them.
//
// Nothing identifying is in here: the payloads carry no address and no player
// name, only the stock map names 0x20 carries ("Canal Crossing", "Great Divide")
// and the random per-session DirectPlay player ids. The generator's --audit pass
// prints every printable run it finds in the plaintext, which is how that stays
// true.
//
// A `Packet` is what the envelope should make of its wire bytes: the u32, the
// subpacket codes in order, and where it came from, so a failure names the
// recording. The round trip is checked in TaPacket.test.cpp.

#include <cstdint>
#include <vector>

namespace rwe
{
    namespace ta_test
    {
        struct Packet
        {
            /** The bytes as they came off the wire, lowercase hex. */
            const char* wire;

            /** The u32 at offset 3, once decrypted and decompressed. */
            std::uint32_t marker;

            /** One two-digit hex code per subpacket, in order. */
            const char* codes;

            /** The recording and transport it was seen in. */
            const char* source;
        };

        inline const std::vector<Packet>& capturedPackets()
        {
            static const std::vector<Packet> all{
"""

FOOTER = """};
            return all;
        }
    }
}
"""


def main():
    audit = "--audit" in sys.argv
    seen = OrderedDict()
    strings = set()
    for name, path in CAPTURES:
        for t, proto, flow, message in read_capture(path):
            payload = ta_payload(message, proto)
            if payload is None or len(payload) < 7:
                continue
            plain, _ = decrypt(payload)
            if len(plain) < 7:
                continue
            expanded = decompress(plain)
            if len(expanded) < 7:
                continue
            wire = bytes(payload)
            if wire in seen:
                continue
            seen[wire] = (
                name + " " + proto,
                int.from_bytes(expanded[3:7], "little"),
                "".join(f"{s[0]:02x}" for s in split_subpackets(expanded[7:])),
            )
            for run in re.findall(rb"[ -~]{4,}", bytes(expanded)):
                strings.add(run.decode())

    print(f"{len(seen)} distinct packets, {sum(len(w) for w in seen)} bytes", file=sys.stderr)
    print("printable runs in the plaintext:", sorted(strings), file=sys.stderr)
    if audit:
        return

    out = [HEADER]
    for wire, (source, marker, codes) in seen.items():
        out.append(f'                {{"{wire.hex()}", 0x{marker:08x}u, "{codes}", "{source}"}},\n')
    out.append(FOOTER)
    path = __file__.rsplit("/", 3)[0] + "/src/rwe/net/ta/ta_packet_captures.h"
    with open(path, "w") as f:
        f.write("".join(out))
    print("wrote", path, file=sys.stderr)


main()
