#version 150

in vec2 fragTexCoord;
in float height;
in float shadeLevel;
out vec4 outColor;

uniform sampler2D textureSampler;
uniform float unitY;
uniform float seaLevel;
uniform float shadeStrength;
// Height of the whole model above unitY.
uniform float unitHeight;

// The construction display, as the original draws it. It keeps an 8-bit
// height per pixel — the model-space Y of the topmost surface there, plus 50 —
// and remaps every pixel by comparing that against a moving threshold. Above
// the line, in a four-unit band on it, and below it are each drawn one of
// four ways, and which three ways depends on how far the build has got.
uniform float buildRatio;
// 0 = not drawn, 1 = build colour A, 2 = build colour B, 3 = the texture.
uniform int aboveMode;
uniform int bandMode;
uniform int belowMode;
// Two triangle waves over palette entries 160..175 at different rates.
uniform vec3 buildColorA;
uniform vec3 buildColorB;

// The band on the line is four of the original's height units tall.
const float bandThickness = 4.0;
// The original's height buffer is the model-space Y biased by 50.
const float heightBias = 50.0;

const vec3 waterTint = vec3(0.5, 0.5, 1.0);
const vec3 normalTint = vec3(1.0, 1.0, 1.0);
// The shaded chain's lighting; see unitTexture.frag, which this must match.
// PALETTE.SHD's row k remaps each texel to the nearest palette entry to
// `colour * 0.06875k`, and row 15 is the identity -- the constant the exe
// hard-codes for a piece the COB has told not to shade. The exact table is a
// nearest-neighbour remap in a 256-entry palette, which would need each
// texel's palette index carried through the atlas to reproduce faithfully;
// that is written up as still to do.
// The row is the original's, exactly -- see the probe in section 13 of
// TOTALA-EXE-SHADING.md, which this reproduces primitive for primitive. What
// a row MEANS is the table below, and it is measured, not fitted:
// tools/exe/shading/shdramp.py reads the shipped PALETTE.SHD and PALETTE.PAL
// and prints exactly this array, each row being the mean of what it does to
// every palette entry bright enough to carry a ratio.
//
// It replaces a two-segment line fitted by hand, which was wrong at the top.
// That fit put row 31 at 1.55 where the real table measures 1.807, so every
// lit face came out dimmer than the original's while the shadows stayed put
// -- which is exactly what makes a model read as though it is carrying too
// much shadow. The dark end is close either way.
//
// One property of the real table does NOT survive being averaged into a
// scalar: the saturation is per colour, not uniform. Palette index 250, a
// pure green, comes back unchanged at every row from 14 to 31, while a mid
// grey brightens by 80%. Reproducing that needs each texel's palette index
// carried through the texture atlas, which is S:15 item 6 of the document and
// is still to do.
//
// Generated by tools/exe/shading/shdramp.py. Do not hand-edit.
const float shadeTable[32] = float[32](
    0.0000, 0.0455, 0.1180, 0.1939,
    0.2676, 0.3438, 0.4085, 0.4733,
    0.5527, 0.6239, 0.6930, 0.7597,
    0.8271, 0.8944, 0.9948, 1.0009,
    1.0577, 1.1367, 1.1970, 1.2827,
    1.3291, 1.3787, 1.4263, 1.4679,
    1.5093, 1.5684, 1.6127, 1.6711,
    1.6957, 1.7392, 1.7793, 1.8070);

float shadeIntensity()
{
    if (shadeStrength <= 0.0)
    {
        return 1.0;
    }

    // The original re-derives the row at every pixel as `sar 16` of the
    // 16.16 interpolant and indexes the table with it, nothing else
    // (TOTALA-EXE-SHADING.md S:21) -- a truncation, so each gradient is
    // quantised into whole rows and a face steps down the table one band at
    // a time. This used to read between the two neighbouring rows to smooth
    // that out; the bands are the original's look, so they stay. Both ends
    // of the interpolation are masked rows in 0..31, so the value cannot
    // leave that range and the original clamps nothing. The min here is
    // against the array bound alone, for a value that lands on 31.00001 in
    // float, and int() truncates toward zero exactly as the shift does.
    float tableValue = shadeTable[min(int(shadeLevel), 31)];

    // Strength blends the measured curve towards "not shaded at all". At 1.0
    // -- the default -- this is the table as measured, row 0 included, which
    // is genuinely black; the original's is too. Below 1.0 it is the same
    // curve with its contrast pulled in around the unshaded colour, an
    // rwe.cfg option for anyone who wants the model to read more softly than
    // the original draws it.
    return mix(1.0, tableValue, shadeStrength);
}

vec3 shadeNormal()
{
    vec3 baseColor = vec3(texture(textureSampler, fragTexCoord));
    return min(baseColor * shadeIntensity() * (height > seaLevel ? normalTint : waterTint), vec3(1.0));
}

void main(void)
{
    // Where this fragment sits in the original's height buffer. It keeps the
    // topmost surface per pixel; shading each fragment by its own height is
    // the same thing wherever the model does not overhang itself, and is
    // better behaved where it does.
    float z = (height - unitY) + heightBias;

    int mode;
    if (z >= buildRatio)
    {
        mode = aboveMode;
    }
    else if (z >= buildRatio - bandThickness)
    {
        mode = bandMode;
    }
    else
    {
        mode = belowMode;
    }

    if (mode == 0)
    {
        // Erased: this part of the model has not been laid down yet.
        outColor = vec4(0.0, 0.0, 0.0, 0.0);
    }
    else if (mode == 1)
    {
        outColor = vec4(buildColorA, 1.0);
    }
    else if (mode == 2)
    {
        outColor = vec4(buildColorB, 1.0);
    }
    else
    {
        outColor = vec4(shadeNormal(), 1.0);
    }
}
