#version 150

in vec2 fragTexCoord;
in float height;
in float shadeLevel;
out vec4 outColor;

uniform sampler2D textureSampler;
uniform float seaLevel;
uniform float shadeStrength;
// How much of its own colour the model keeps where it covers the screen. 1 for
// everything except a cloaked unit, which the original averages with whatever
// is behind it. See RenderService::drawUnitMeshBatch.
uniform float alpha;

const vec3 waterTint = vec3(0.5, 0.5, 1.0);
const vec3 normalTint = vec3(1.0, 1.0, 1.0);
// TA lights its models after all. The renderer decoded earlier -- no normals,
// no sun, texels copied unmodified -- is the one that runs with SHADING
// switched OFF; the option defaults ON, and 0x458744 picks between two
// complete rasterizer chains on that one bit. The shaded chain averages the
// unit normals of the polygons meeting at a vertex and takes
//
//     level = (int)(5.0 * dot(n, (-0.8, 1.0, 0.25))) & 0x1F
//
// as a row of PALETTE.SHD. Three things about that line matter here. The mask
// WRAPS, and reproducing the wrap rather than clamping to the table's ends is
// what finally matched the original's contrast -- a screenshot comparison
// settled it against the earlier reading, which is why nothing below clamps
// to an end. The level is computed and masked per VERTEX, not per pixel, so
// unitTexture.vert does that arithmetic and only the resulting row arrives
// here interpolated. And the sun vector is not normalised: its length of
// 1.3048 sets the ramp's width at about thirteen rows rather than thirty-two.
//
// PALETTE.SHD's row k remaps each texel to the nearest palette entry to
// `colour * 0.06875k`, and row 15 is the identity -- the constant the exe
// hard-codes for a piece the COB has told not to shade. The exact table is a
// nearest-neighbour remap in a 256-entry palette, which would need each
// texel's palette index carried through the atlas to reproduce faithfully;
// that is written up as still to do.
// The row is the original's, exactly -- see the probe in section 13 of
// TOTALA-EXE-SHADING.md, which this reproduces primitive for primitive. What
// a row MEANS is the table below, and it is measured, not fitted:
// tools/exe/shading/shdramp.py reads the shipped PALETTE.SHD and PALETTE.PAL
// and prints exactly this array, each row being the mean of what it does to
// every palette entry bright enough to carry a ratio.
//
// It replaces a two-segment line fitted by hand, which was wrong at the top.
// That fit put row 31 at 1.55 where the real table measures 1.807, so every
// lit face came out dimmer than the original's while the shadows stayed put
// -- which is exactly what makes a model read as though it is carrying too
// much shadow. The dark end is close either way.
//
// One property of the real table does NOT survive being averaged into a
// scalar: the saturation is per colour, not uniform. Palette index 250, a
// pure green, comes back unchanged at every row from 14 to 31, while a mid
// grey brightens by 80%. Reproducing that needs each texel's palette index
// carried through the texture atlas, which is S:15 item 6 of the document and
// is still to do.
//
// Generated by tools/exe/shading/shdramp.py. Do not hand-edit.
const float shadeTable[32] = float[32](
    0.0000, 0.0455, 0.1180, 0.1939,
    0.2676, 0.3438, 0.4085, 0.4733,
    0.5527, 0.6239, 0.6930, 0.7597,
    0.8271, 0.8944, 0.9948, 1.0009,
    1.0577, 1.1367, 1.1970, 1.2827,
    1.3291, 1.3787, 1.4263, 1.4679,
    1.5093, 1.5684, 1.6127, 1.6711,
    1.6957, 1.7392, 1.7793, 1.8070);

float shadeIntensity()
{
    if (shadeStrength <= 0.0)
    {
        return 1.0;
    }

    // The original re-derives the row at every pixel as `sar 16` of the
    // 16.16 interpolant and indexes the table with it, nothing else
    // (TOTALA-EXE-SHADING.md S:21) -- a truncation, so each gradient is
    // quantised into whole rows and a face steps down the table one band at
    // a time. This used to read between the two neighbouring rows to smooth
    // that out; the bands are the original's look, so they stay. Both ends
    // of the interpolation are masked rows in 0..31, so the value cannot
    // leave that range and the original clamps nothing. The min here is
    // against the array bound alone, for a value that lands on 31.00001 in
    // float, and int() truncates toward zero exactly as the shift does.
    float tableValue = shadeTable[min(int(shadeLevel), 31)];

    // Strength blends the measured curve towards "not shaded at all". At 1.0
    // -- the default -- this is the table as measured, row 0 included, which
    // is genuinely black; the original's is too. Below 1.0 it is the same
    // curve with its contrast pulled in around the unshaded colour, an
    // rwe.cfg option for anyone who wants the model to read more softly than
    // the original draws it.
    return mix(1.0, tableValue, shadeStrength);
}

void main(void)
{
    vec4 baseColor = texture(textureSampler, fragTexCoord);
    if (baseColor.a < 0.5)
    {
        discard;
    }

    vec3 lit = vec3(baseColor) * shadeIntensity() * (height > seaLevel ? normalTint : waterTint);
    outColor = vec4(min(lit, vec3(1.0)), alpha);
}
