#pragma once

// A sample of the TA packets in the spike's captures, as they came off the wire.
//
// Generated by tools/ta-net/ta-packet-captures.py from ta-baseline.pcap,
// ta-options.pcap and ta-small.pcap, the three recordings of a real Total
// Annihilation playing over DirectPlay that the spike took. The captures hold
// 2907 packets, 1497 distinct on their wire bytes. A shape here is the framing,
// whether the u32 is a reply's 0xffffffff or a sender's own count, and the
// sequence of subpacket codes with repetition collapsed -- so a packet of
// thirty-one 0x1a records is one shape and not thirty-one, which is 36 shapes
// rather than 121. At most two per shape are kept, spread over the shape's
// range of sizes, so a run is represented by its shortest and its longest
// instance. Between them the 59 here cover all 25 codes the captures hold, both
// framings, both shapes of the u32, and every packet size from 8 bytes to the
// 711-byte one, for 14 KB instead of 265 KB. The generator asserts that
// coverage rather than trusting the rule to produce it.
//
// Sanitised on the way in, and the substitutions are these. The only text a TA
// packet carries is the map name in a 0x20 -- fifteen bytes NUL-padded at
// offset 1, and in the captures "Canal Crossing" or "Great Divide", both stock
// vanilla map names. 7 packets carried one and were re-packed and
// re-encrypted with it replaced by "Sanitised Map", the same length and padded
// the same way; the rest already had the field empty. A sample that would not
// survive the rewrite was dropped, and the generator says which.
//
// No player name is here because no player name is in a TA packet: the captures
// carry them in the DirectPlay system messages, in the SUPERENUMPLAYERSREPLY
// (command 0x29) as UTF-16, and `ta_payload` drops those before any of this.
// The handle this repository's own history carries is there and not here, and
// `--audit` checks for it by name in both encodings. There is no address in a
// TA packet either: what reads as a dotted quad in 0x1a, 0x2c and 0x28 is four
// bytes of a CRC or a 16.16 coordinate.
//
// The generator's --audit pass prints every printable run in the result and
// checks those handles against it, so the claim above stays checkable.
//
// A `Packet` is what the envelope should make of its wire bytes: the u32, the
// subpacket codes in order, and where it came from, so a failure names the
// recording. The round trip is checked in TaPacket.test.cpp.

#include <cstdint>
#include <vector>

namespace rwe
{
    namespace ta_test
    {
        struct Packet
        {
            /** The bytes as they came off the wire, lowercase hex. */
            const char* wire;

            /** The u32 at offset 3, once decrypted and decompressed. */
            std::uint32_t marker;

            /** One two-digit hex code per subpacket, in order. */
            const char* codes;

            /** The recording and transport it was seen in. */
            const char* source;
        };

        inline const std::vector<Packet>& capturedPackets()
        {
            static const std::vector<Packet> all{
                {"03c705fbfbfaf9055811d3030c0d0e0f640ed908", 0xfffffff8u, "02", "baseline UDP"},
                {"03e106fcfbfaf9055811d3035c15d707640ed908", 0xffffffffu, "02", "baseline UDP"},
                {"03ef06bafbfaf905b19be3030c0d0e0fdaeee608", 0xffffffb9u, "02", "options UDP"},
                {"035409fcfbfaf905b19be303cc9fe707daeee608", 0xffffffffu, "02", "options UDP"},
                {"03ef01f4fbffff06", 0xfffffff7u, "06", "baseline TCP"},
                {"03da01dffbffff06", 0xffffffdcu, "06", "baseline TCP"},
                {"04991b03f6faf9f80e29596a0c63677b7962777734f55b7668391a401d331c31233e0c270a2078267628742a29ed2d2f30453cea3c3436361a39fb323e3d3a6e414b42434e45bc474b48634e98f320155175205a050000", 0xfffffff2u, "062024", "baseline TCP"},
                {"04961c03b2faf9f80e29596a0c63677b7962777734f55b7668391a401d331c31233e0c270a2078267628742a29ed2d2f30fbdcd53c3436361a39fb323e3d3a6e414b42434e45bc474b48634e98f320155175205a050000", 0xffffffb6u, "062024", "options TCP"},
                {"045d250389faf9f80e2fc2e564eb06c5911112ee14eb1637184a7b757569776c45e1460369445607d629f62f13932b91368f358d3ccb36c9383cfa3f3f3d4c3f41414242446547474a1e4eba4c474e4f5a51a85357547f528ce734a15c792c5f050000", 0xffffff8du, "06262024", "options TCP"},
                {"043923038ffaf9f80e2f0e99640b0709911112ee14eb1637184a7b757569776c45e1460369445607d629f62f13932b91368f358d3ccb36c9383cfa3f3f3d4c3f41414242446547474a014eba4c474e4f5a51a8535754cc6f8c81bea15c792c5f010000", 0xffffff8bu, "06262024", "small TCP"},
                {"03f701fcfbffff07", 0xffffffffu, "07", "baseline TCP"},
                {"03ea03fcfbfaf9071801", 0xffffffffu, "0718", "baseline TCP"},
                {"04550e41fb140600120d0a8e0c20f00df0117d136b149915871ab51fa318e1d026fe25cc2cda2f2823362604211c202e000000", 0xffffffffu, "071a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a", "small TCP"},
                {"04ba1d41fb140600120d0a8e0c20f00df0117d136b149915871ab51fa318e1d026fe25cc2cda2f2823362604211220d07f3e6d235b244925b72aa52f93288129bf8e559c5caa5fb852465654516250704f5e1d730b743875000004", 0xffffffffu, "071a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a", "small TCP"},
                {"03ea03fcfbfaf9071e01", 0xffffffffu, "071e", "baseline TCP"},
                {"037e04fcfbfaf900177d0ed908", 0xffffffffu, "071f", "baseline TCP"},
                {"031004fcfbfaf900170f920609", 0xffffffffu, "071f", "small TCP"},
                {"0393029efbfaff0806", 0xffffff9du, "0806", "baseline TCP"},
                {"03790284fbfaff0806", 0xffffff87u, "0806", "small TCP"},
                {"038412aefafaf908f5040a8a0c02f31f1090121ce90416951816e7081c9f1e10dd3522a1242adb3f28ac2a27d02d5821e939ce006483", 0xfffffeadu, "0f0f0f0f0f0f0c", "baseline UDP"},
                {"04de0c0704fa2607190b0a0a1e446f0f1001d2130715391634e9111b351e2e1e1021d22365278c0da02b01132f01c62c1da936291a7d3318bd3b000000", 0xffffff00u, "1112102c2c2c2c2c2c2c", "small UDP"},
                {"03d601dbfbffff15", 0xffffffd8u, "15", "baseline TCP"},
                {"03ac01b1fbffff15", 0xffffffb2u, "15", "small TCP"},
                {"03ed02f8fbfaff1700", 0xfffffffbu, "17", "baseline TCP"},
                {"03f102fcfbfaff1700", 0xffffffffu, "17", "baseline TCP"},
                {"03f102fcfbfaff1801", 0xffffffffu, "18", "small TCP"},
                {"037b04fcfbfaf91d09090a0b0c0d0e0f1007010000", 0xffffffffu, "1a", "baseline TCP"},
                {"03b304fcfbfaf91d0c090a0b0c0d0e0f103c020000", 0xffffffffu, "1a", "baseline TCP"},
                {"04153621fb14061d0c097f0b210ff3df10164e135b144915771a651f9318e180268e259c2cea2ff822c621d4202220d02f3e1d230b247925672a552f4328b129bfde55ec5cfa5f88529651a450b253404fae4d737b746975177a057f33782179ef469dfc4cca4fd842a641b4408243905e7e428c6b445945474a354f23481149ffb60dbbbb1abf28b236b144b0048e00002d", 0xffffffffu, "1a071a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a", "options TCP"},
                {"04790321fb14061d0c097f0b210f09df104d12000004", 0xffffffffu, "1a1a", "baseline TCP"},
                {"04841021fb14061d0c097f0bf20cf17f104e127c156a14981b861eb419a218e0ef26fd2bcb2cd92d27253526032316203ace333c33000000", 0xffffffffu, "1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a07", "baseline TCP"},
                {"041c1321fb14061d0c097f0b210ff1df104e127c156a14981b861eb419a218e0ef26fd2bcb2cd92d2725352603231120ef7e226c255a24482bb22e3c6028000000", 0xffffffffu, "1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a071a", "options TCP"},
                {"041b9121fb14061d0b097b0b1e6d1e98f310122514a4c7fc39f01a216e77fac721019201ae8c24e845dfa328db386aa6d7e9337e9f9c7f32b5b13393d4853c1cc1af4b44542027bca1714cd376a50ca548566738dfbe2e53b9dddbacd5577770208d9a64742b84fa85316f2bf6674c8108757a09007c783cad3b8a92725851e26ff989a80c421176108a4aad4b049f9f9de2a8610c9f7f1ace88d3887ffe7ed6b3ce614d85acb381068259b3ab8f3a8dfb78a4b564641fa0ac49f85e75ab8ca708357ad3ee4d2e533e51db787555e7d4d8c4231bddc9d1beef2ecb63cb2455be29fcfd025fc42ffa02d3d21334e54bb6d2a39bd35d244cbed9f712b91e94de7a6160fb7b24980e1607f29214f9e226f3010931976091bf328dfcc43a953bbf000fdc5a04809f649e6101c485b3d29c0a2833330000ee", 0xffffffffu, "1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a18", "baseline TCP"},
                {"04c72521fb14061d0c097f0b210ff1df104e127c156a14981b861eb419a218e0ef26fd2bcb2cd92d2725352603231120cf7e226c255a24482bb62ea42992288057be8d5b9b5ca95db7524556535361506f71ad1c750a74387b267ed479c278f047de4a66a34c61000004", 0xffffffffu, "1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a07", "options TCP"},
                {"04452721fb14061d0c097f0b210ff1df104e127c156a14981b861eb419a218e0ef26fd2bcb2cd92d2725352603231120cf7e226c255a24482bb62ea42992288057be8d5b9b5ca95db7524556535361506f71ad1c750a74387b267ed479c278f047de4a6cab4cb94d8942000000", 0xffffffffu, "1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a", "baseline TCP"},
                {"04e313e7fafa26072809650b730c810d2f8e11bc10aa13d81ec61dfa1418de1f2321562dfd2d2727a6d62a228c24a627543131c93d20553d1c5b333e000000", 0xfffffffeu, "2024", "baseline TCP"},
                {"04fe1b03f2faf9f8285a6b650c647a666374763359e577673819511a021f001c3e252d3d216b276929672b2eec2e2e2f443feb3b3535c93778393b3b3e3d3a7e414b42434e45bc474b4863e349f320055175305a050000", 0xfffffff6u, "2024", "baseline TCP"},
                {"04fd0301fb140626097d04d204141d0f1067971300000e", 0xffffffffu, "2121", "baseline TCP"},
                {"040d0301fb140626090f980d05141d0f10159713000092", 0xffffffffu, "2121", "small TCP"},
                {"038906d2fbfaf9250e9b0c020e2f0a9d161813311087060901", 0xffffffd1u, "222222", "small TCP"},
                {"04ad0507b3fa26072a7d04d204650c2d66601212ae15000008", 0xffffffb7u, "22222222", "baseline TCP"},
                {"039a05fcfbfaf9240c9b0c020a9f08061010000000", 0xffffffffu, "23", "small TCP"},
                {"03aa04f0fbfaf9230e9b060900", 0xfffffff3u, "24", "small TCP"},
                {"038004c8fbfaf9230c9b060900", 0xffffffcbu, "24", "small TCP"},
                {"04330811fb14062f08660a0b7649a77311595127153ab415599d1a1ffc5d000000", 0xffffffffu, "28", "baseline UDP"},
                {"04830e11fb14062f08670aeff474044b701168ba150352a32639235a19c6127e22e163b3d81da818182a9a6a000030", 0xffffffffu, "28", "baseline UDP"},
                {"038d039ffbfaf92a0006", 0xffffff9cu, "2a06", "baseline TCP"},
                {"03730385fbfaf92a0006", 0xffffff86u, "2a06", "small TCP"},
                {"04562503d7faf9f8226d03290c0d0f0f1011c20d14311641a9191a002e1c1e1f20302323250575464629435f455e4b4b107cca524415b2365e3ad438d239d03a4faf445d475b45594b4c8a484c1d3a418959a35254c456655c595eea5c575e55609be26367644f62d607706896495c64050000", 0xffffffd3u, "2a09112024", "baseline UDP"},
                {"0467270385faf9f8226d03294c0d0f0f10117eb214401ba6184bb81bad1d0f1e202022037744484e5c4059ab49490e62514112b735ca5034d63ad43fd238d0395e425c405a464642884a4a4fde4b470cf151a35254671e53e959505b5c575ea5606263f9cc5dbe83726a4e5967010000", 0xffffff81u, "2a09112024", "small UDP"},
                {"035805d1fbfaf92b06090b0b0c0d0e0f32e1ff1f00", 0xffffffd2u, "2c", "baseline UDP"},
                {"030a0583fbfaf92b06090b0b0c0d0e0f32e1ff1f00", 0xffffff80u, "2c", "small UDP"},
                {"04601d03f4fbf9f824070a84080e0eae1033e2ec0b155e1e9f19881b9c1cde1f74845322f49427e95be92a3b9c2c4e3e3030872696356e341441313bac5c3f0f40f1404240d4730f4cdbb24fdf084a000010", 0xfffffef0u, "2c09102c2c2c2c", "small UDP"},
                {"04c9180726fa260724070a580e0f0eae1033e2ec0b151f435619881bf4ac1e4b51208a7125e52766a9992b3b1c2f3f1f3030622096356e34143265eb3d5c3f0f40f1404240100e431e9cb24f1be54b1708570b1650000000", 0xffffff22u, "2c09102c2c2c2c2c2c", "small UDP"},
                {"04f41103d6fbf9f824020a4444090e0f201113134515461280194b8e1c0c1d1f2133cb52262536672a3a7a2a622e9f2e9a637a3267ad3263703c6fce3d3c000000", 0xfffffed2u, "2c2c2c1112102c2c2c2c", "small UDP"},
                {"04a907077afa260724020a9e0c5e9e0f201113134515808f188e17531d858b1f00000b", 0xffffff7eu, "2c2c2c2c", "baseline UDP"},
                {"04255803aafbf9f824020a7044080e0f2011131345156a02801967531d638b1f2cda2233522bff2f082a4eab230dd335307d32f3372e362175283edb3f732f3b61411012354142471e7a4f1cdf48163aa15454605252c5513859585c4ef00d5844526443623c7760611a624170be664a43785c007c77768d226870782f77fe79428bc284a68e718780eb80cb8ed69d85d29df29b36993967999b977b9aff939513ac84f0a918a6acf4daa749a26da6edbfbd21bc42bb65b938b5e708b07fae3fcfe3d378a4ce44d6c51adb6bcb8fdcda63c12fd3d68ba5c7baca7ad11ece1ed1c2f50923f567f2e85dfab5f8e14ffbcfff0cf0e5fca6e0f7f63bec1bf3dfe9bf10d680148417e4101e3a12239f184e1cee716100760cb601da00da0f3e07de08cda33833773c663e49da218937cd3bd0322d522756295626fa255a2c1e20fe25afc35fc34de75dc7532b195eee534e5eaf534d13423749574f9b459b417f7e7f7bd6e0438477844747fa74cb750e7d738f7350d36b17547765bb581b615f5d5f923e00a044a564a4a89188a96c96ea3cb16e90b6d48af4b298ba58befc87bcb980b4dd21828582458e298ee98badab0d979c4f4690d0c5957a913aa39e943e9e02e93f63eca3b5db8ae3aaeb6ee7eee8d2fa6df3f5b7fd97f01bf13bd5fff2ecd3cb9f63fa8255f9aac4aac94ec04eca98caa1d496dbe544d699d3d9d3d7fe5d6a902e320469f7283a3a3ab3270d7e9c3c13233324644527c3db2bdb3a6f0d1ba2130bf0162514486a1a6a1aae1f0e0543821851002ce9840cf91319099d0fbd75751177c468a8333b4de87dac693b5c7e33655361ea9460b86f78639c6f3c68205514d043d0245e58fa535e5f540e5d0760591965c64c636b4256c8461d5d07dff2b6c1b8e5bd25b429a4f15f94f52083ba50ae94aeb4a980eaa4bbe9a344e3f19880309b059cd99b97c8ebdbad96cdf0c1b0cc67f534f678873aa4cfb9fcfdc0c9828100007e", 0xfffffeaeu, "2c2c2c2c0c0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f", "baseline UDP"},
                {"04ee0f070cfa260724020a560fa90e0f201113134515488f183345531d7de61e41b42232d8ad26263af929d02c3d1e2b5e2282319a3127345a6c390000fc", 0xffffff08u, "2c2c2c2c2c1112102c", "baseline UDP"},
                {"042f0b073dfa260724020a920fa90e0f2011131345158c8f18b381531d81e61ebd8920bdb12527000000", 0xffffff39u, "2c2c2c2c2c2c", "baseline UDP"},
};
            return all;
        }
    }
}
